version: 2.1

orbs: 
  node: circleci/node@5.0.2

workflows:
  main-workflow:
    jobs:
      - affected
      - echo:
          matrix:
            parameters:
              function-name: [docker, linux, macos]

jobs:
  affected:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn list:affected

  echo:
    parameters:
      function-name:
        type: string
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn echo << parameters.function-name >>
