version: 2.1

orbs: 
  node: circleci/node@5.0.2

workflows:
  main-workflow:
    jobs:
      - affected

jobs:
  affected:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn list:affected
