version: 2.1

orbs: 
  node: circleci/node@5.0.2

workflows:
  main-workflow:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages
      - run:
        command: yarn build:affected
