version: 2.1

orbs:
  node: circleci/node@5.0.2
  gcp-cli: circleci/gcp-cli@2.4.1

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - run: yarn cli create-deployment-config
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy-cloud-functions:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run: |
          if ! grep -q cloud-functions ./tmp/deployment.txt; then
            circleci-agent step halt
          fi
      - gcp-cli/install:
          version: 398.0.0
      - gcp-cli/initialize
      - run: yarn cli deploy-cloud-functions --affected

workflows:
  deploy:
    when:
      or:
        - equal: [main, << pipeline.git.branch >>]
    jobs:
      - build
      - deploy-cloud-functions:
          requires:
            - build
