version: 2.1

setup: true

orbs:
  node: circleci/node@5.0.2
  continuation: circleci/continuation@0.3.1

jobs:
  affected:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: node ./scripts/list-deploy-functions.mjs
      # - run: node ./scripts/create-dynamic-config.mjs
      - persist_to_workspace:
          root: ./tmp
          path:
            - functions-to-deploy.txt

  setup:
    executor: continuation/default
    steps:
      - attach_workspace:
          at: ./tmp
      - run: cat ./tmp/functions-to-deploy.txt
      # - continuation/continue:
      #     configuration_path: ./circleci/generated/generated_config.yml

workflows:
  setup:
    jobs:
      - affected:
          filters:
            branches:
              only: main
      - setup:
          requires:
            - affected
          filters:
            branches:
              only: main
